# .github/workflows/sync-to-hf-space.yml
name: Sync to Hugging Face Space

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 # Use v4 for latest features
        with:
          fetch-depth: 0
          lfs: true # Explicitly enable LFS checkout

      # It's good practice to ensure git-lfs is installed on the runner, though checkout might handle it
      - name: Install Git LFS
        run: |
          sudo apt-get update
          sudo apt-get install -y git-lfs
          git lfs install --system --skip-repo # Install LFS globally for the runner

      - name: Push to Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          SPACE_ID: GuitarGeorge/Prophet-commodity-stock-analysis
        run: |
          echo "Attempting to push to Hugging Face Space: $SPACE_ID"
          
          # Configure Git user
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"

          # Add Hugging Face as a remote with token for authentication
          # No need for dummy username when token is passed this way for hf.co
          git remote add hf_space "https://:${HF_TOKEN}@huggingface.co/spaces/${SPACE_ID}"
          
          git remote -v

          # Fetch LFS objects before pushing. This ensures they are available.
          # This step is crucial for ensuring LFS files are uploaded during the push.
          git lfs fetch --all origin # Fetch LFS objects from your GitHub origin
          git lfs push --all hf_space # Push LFS objects to the hf_space remote

          # Push the Git refs (commits, branches)
          # Use HEAD:refs/heads/main to push the current commit of the local main to the remote main
          git push --force hf_space HEAD:refs/heads/main
          
          echo "Push to Hugging Face Space completed."